id: I54663F97
ocr_import_info:
  timestamp: '2023-09-28T04:49:42.933278+00:00'
  batch_id: batch-cdce
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-28 05:16:46.774703+00:00
last_modified: 2023-09-28 05:16:46.774711+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W20482
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW20482
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མཛོད་འགྲེལ་མངོན་པའི་རྒྱན།
  languages:
  - bo
  author: མཆིམས་འཇམ་པའི་དབྱངས།
statistics:
  ocr_word_mean_confidence_index: 0.997845675027972
  ocr_word_median_confidence_index: 1.0
bases:
  I4694:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4694
      total_pages: 782
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4694.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.997845675027972
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
